### ISSUE TITLE
Add Dependabot for Automatic Dev Container Updates

### ISSUE THREAD

**Issue by Maykon-JDS** [Maykon-JDS/converter#5]
## Description
We need to configure Dependabot to automatically update the Dev Container features in the repository. This will ensure that our development containers are always using the latest published versions of the features.

## Tasks
- [ ] Create a `.github/dependabot.yml` file in the root directory.
- [ ] Configure the `dependabot.yml` file to target the `devcontainers` package ecosystem.
- [ ] Set the update schedule to weekly for automatic version updates.
- [ ] Ensure that the Dev Container configuration files (`devcontainer.json` and `.devcontainer-lock.json`) are included in the updates.
- [ ] Verify that Dependabot is correctly generating pull requests for updates.

## Acceptance Criteria
- Dependabot is configured to update Dev Container features weekly.
- Pull requests are automatically generated for Dev Container feature updates.
- The repository is using the latest versions of the features defined in the `devcontainer.json`.

## Additional Information
For more information on configuring Dependabot, refer to the [official documentation](https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates).
